sudo: require
services: 
 - docker

before_install:
 - docker build -t dawidmbury/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true dawidmbury/docker-react npm run test -- --watchAll=false